### ISSUE TITLE
js加密成jsc的问题

### ISSUE THREAD

**Issue by quert999** [Mas0nShi/Mas0nShi#1]
大师你好，想问下js加密到jsc咋操作的，使用你的[jsc-Decryption](https://github.com/Mas0nShi/jsc-Decryption)解密了，但是我用zlib加密就过不去，我现在js文件是走的gzip那个if分支

**Comment by Mas0nShi** [comment]
引用 repo 已不再维护，请使用 [jscHookR](https://github.com/Mas0nShi/jscHookR) 进行动态替换。

> 大师你好，想问下js加密到jsc咋操作的，使用你的[jsc-Decryption](https://github.com/Mas0nShi/jsc-Decryption)解密了，但是我用zlib加密就过不去，我现在js文件是走的gzip那个if分支
